// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfewwgyfzldkkyaymjai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXd3Z3lmemxka2t5YXltamFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDM5OTIsImV4cCI6MjA2NTA3OTk5Mn0.LIpenpT2Ph1nsj-jhU9HXvi3XhKuJwtdEgmv1Lb94fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);